version: '3.9'
services:
  app:
    image: node:20.0-bullseye-slim
    user: node:node
    container_name: node
    restart: unless-stopped
    working_dir: /usr/src/app
    command: npm start
    volumes:
      - .:/usr/src/app
